### ISSUE TITLE
TASK #A2.0 | User DB, Authentication & Log In #1

### ISSUE THREAD

**Issue by isilvestrov** [whereAt-Industries/Butterfly.W.#2]
This Task builds on top of 
TASK #A1.0 | User DB, Authentication & Log In #1 

Task at hand:
Create a front end “widget” that will be populated with the user Info from the DB. 
Also, create the YES / NO button to capture the users choice. [Default : YES]

For button highlight use html #0000cc

See Image for the concept layout
![user widget v1 0](https://cloud.githubusercontent.com/assets/5764117/9629594/1e05af80-5174-11e5-928d-30449b15f6f1.jpg)

// Logic for the Button determining the email prefferences.
IF the button is set to “YES” THEN
     SET alerts to alerts.ON
    Display button toggle backlight of “YES” In #0000CC 
ELSE 
    SET alerts to alerts.OFF
     Display button toggle backlight of “NO” In #0000CC 
ENDIF
// THEN set either  alerts.ON or alerts.OFF into the user.DB table

---

Also:
IF $Gender is set to $M THEN
Disaplay : man.png
ELSE IF $Gender is set to $F
Disaplay : woman.png
ENDIF

Resources : 
LOGO:
 http://www.whereatcloud.com/wp-content/uploads/2015/02/Logo_FINAL-int-indx240.png

Picture of man:
http://www.whereatcloud.com/wp-content/uploads/2015/09/man.png

Picture of woman:
http://www.whereatcloud.com/wp-content/uploads/2015/09/woman.png

**Comment by davidsemakula** [comment]
@isilvestrov Since no code for TASK #A1.0 is available in the repo should this widget just assume existence of the user info variables in php?

Or should this be implemented in Javascript with something like

``` javascript
var userInfo = {
 company: 'whereAt Industries',
 ...
 firstname: 'Ivan'
 ...
 alerts: 'ON'
};
```

with a click on the YES/NO button toggling the value of alerts on the Javascript object

**Comment by isilvestrov** [comment]
Hi @davidsemakula , 

Yes, you can assume the existence of the said values in the following format.

![user db layout](https://cloud.githubusercontent.com/assets/5764117/9734525/046cde12-5634-11e5-9197-b3fd616e3051.png)

Although the "caputre" the choice is missing at this moment, it still remain a requirement.
I will try to get you the api access a.s.a.p.

---

Also:
Format in POST key/value pairs: 
apiKey : <   API key> 
userName : <  username> 
password : <   password>

**Comment by davidsemakula** [comment]
@isilvestrov going to implement this with:
- user info set statically in PHP
- YES/NO button connected to a javascript function that could be used to call API to save choice

**Comment by davidsemakula** [comment]
@isilvestrov Checkout https://github.com/whereAt-Industries/Butterfly.W./pull/4

**Comment by davidsemakula** [comment]
Hi @isilvestrov 
Let me know if https://github.com/whereAt-Industries/Butterfly.W./pull/4 fixes this issue or if further changes are necessary.
