### ISSUE TITLE
TASK #A3.0 | User DB, Authentication & Log In 

### ISSUE THREAD

**Issue by isilvestrov** [whereAt-Industries/Butterfly.W.#3]
Front End.

This Task builds on top of 
TASK #A1.0 | User DB, Authentication & Log In #1 
and
TASK #A2.0 | User DB, Authentication & Log In #2 

Task at hand:
To Create a Log in Screen, which Authenticates based on the $id + $password combination. 

![log in screen](https://cloud.githubusercontent.com/assets/5764117/9629925/cd44db04-5176-11e5-8c68-ddc9b4a5087d.jpg)

---

THE LOG IN SCREEN
USE : G-Maps API Zoom : 12  // this is a nice to have. We can integrate maps.api with our own tracking code later.

Menu : 
            528px \* 328 px Padding : 20px  ;  
           Centered! // Both Vertical & Horizontal
For the Buttons: 
ON CLICK:
           LOG IN : > Go to //http: widget from #2  // Use color #0000CC
           SIGN UP :  >  Go to Home ( www.whereatcloud.com) // Use color #00FF00    

The text : 
SMART LOGISTICS PLATFORM // Upper Case ; 14px
Private Beta // Italic; 14 px
by // 10px
whereAt Industries // 14px; "At" in bold.

For "Username" and "Password" use 12px.

Resources : 
LOGO:
http://www.whereatcloud.com/wp-content/uploads/2015/02/Logo_FINAL-int-indx240.png
*Note: this Logo is stationary and is does not have to be called upon from the database described in #1

**Comment by davidsemakula** [comment]
Checkout https://github.com/whereAt-Industries/Butterfly.W./pull/5

**Comment by davidsemakula** [comment]
Hi @isilvestrov 
Let me know if https://github.com/whereAt-Industries/Butterfly.W./pull/5 fixes this
